apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@podbox.io # Update this if needed
    privateKeySecretRef:
      name: letsencrypt-prod-dns-account-key
    solvers:
    - dns01:
        cloudflare:
          email: admin@podbox.io # Update this if needed
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
